#ifndef __FSMSTATES_H__
#define __FSMSTATES_H__

enum MainFSMState {
    FSM_START = 0,
    FSM_TEXTSCROLLER = 1,
    FSM_TEXTSCROLLER_FINISHED = 2,
    FSM_SHOWLOGO = 3,
    FSM_SHOWLOGO_FINISHED = 4,
    FSM_ROTATINGCUBE = 5,
    FSM_STOP = 6,
    FSM_ERROR = 7,
    FSM_QUIT = 8
};

#endif
