#ifndef __FSMSTATES_H__
#define __FSMSTATES_H__

enum MainFSMState {
    FSM_START = 0,
    FSM_TEXTSCROLLER = 1,
    FSM_TEXTSCROLLER_FINISHED = 2,
    FSM_SHOWLOGO = 3,
    FSM_SHOWLOGO_FINISHED = 4,
    FSM_ROTATINGCUBE = 5,
    FSM_ROTATINGCUBE_FINISHED = 6,
    FSM_MANDELBROT = 7,
    FSM_MANDELBROT_FINISHED = 8,
    FSM_STOP = 9,
    FSM_ERROR = 10,
    FSM_QUIT = 11
};

#endif
